name: Minelife
version: '${project.version}'
main: cz.minelife.Main
api-version: 1.18

commands:
  startSession:
    description: Vybrání boogeymana
    usage: /startSession
  setupCmd:
    description: Nastavení serveru
    usage: /setupCmd
  endSession:
    description: Konec
    usage: /endSession