name: Minelife
version: '${project.version}'
main: cz.minelife.Main
api-version: 1.18

commands:
  setupCmd:
    description: Nastavení serveru
    usage: /setupCmd
  boogeyman:
    description: Vybrání boogeymana
    usage: /boogeyman